name: medicinal_leaf_scan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
  #logo appapp
    - assets/IconApp/logo_app.png  
  #logo navigation bottom
    - assets/logo_navigation/history_icon.png
    - assets/logo_navigation/setting_icon.png
    - assets/logo_navigation/scan_icon.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/IconApp/logo_app.png" 
  remove_alpha_ios: true
