name: medicinal_leaf_scan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  path: ^1.9.1
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  google_mlkit_text_recognition: ^0.15.0
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
  #logo app
    - assets/IconApp/logo_app.png  
  #logo navigation bottom
    - assets/logo_navigation/history_icon.png
    - assets/logo_navigation/setting_icon.png
    - assets/logo_navigation/scan_icon.png
  #logo history
    - assets/logo_history/history.png
    - assets/logo_history/save.png
  #load
    - assets/load/load1.gif
    - assets/load/load.json

  #icon setting
    - assets/icon/account.png
    - assets/icon/book.png
    - assets/icon/Info.png
    - assets/icon/feedback.png
    - assets/icon/privacy_policy.png
    - assets/icon/terms-and-conditions.png
    #models
    - assets/models/models.tflite
    - assets/models/labels.txt


flutter_icons:
  android: true
  ios: true
  image_path: "assets/IconApp/logo_app.png" 
  remove_alpha_ios: true
