name: medicinal_leaf_scan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
  #logo app
    - assets/IconApp/logo_app.png  
  #logo navigation bottom
    - assets/logo_navigation/history_icon.png
    - assets/logo_navigation/setting_icon.png
    - assets/logo_navigation/scan_icon.png
  #logo history
    - assets/logo_history/history.png
    - assets/logo_history/save.png

  #icon setting
    - assets/icon/account.png
    - assets/icon/book.png
    - assets/icon/Info.png
    - assets/icon/feedback.png
    - assets/icon/privacy_policy.png
    - assets/icon/terms-and-conditions.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/IconApp/logo_app.png" 
  remove_alpha_ios: true
