// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CYWc0blcc8TliRxoByehgZjcs-V8Kxg',
    appId: '1:427061760676:web:293b6b2aaec2a91c540c31',
    messagingSenderId: '427061760676',
    projectId: 'medicinal-leaf-scan',
    authDomain: 'medicinal-leaf-scan.firebaseapp.com',
    storageBucket: 'medicinal-leaf-scan.firebasestorage.app',
    measurementId: 'G-XB2H9SRC4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnbUMX4xonypepgwU6RqMltHr67SrcrKM',
    appId: '1:427061760676:android:7a258dfe902bf8c0540c31',
    messagingSenderId: '427061760676',
    projectId: 'medicinal-leaf-scan',
    storageBucket: 'medicinal-leaf-scan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3qP7qbYi_ULShrCYrt9vh4cvGrsfu8vM',
    appId: '1:427061760676:ios:7bcc611cba32de16540c31',
    messagingSenderId: '427061760676',
    projectId: 'medicinal-leaf-scan',
    storageBucket: 'medicinal-leaf-scan.firebasestorage.app',
    iosBundleId: 'com.example.medicinalLeafScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3qP7qbYi_ULShrCYrt9vh4cvGrsfu8vM',
    appId: '1:427061760676:ios:7bcc611cba32de16540c31',
    messagingSenderId: '427061760676',
    projectId: 'medicinal-leaf-scan',
    storageBucket: 'medicinal-leaf-scan.firebasestorage.app',
    iosBundleId: 'com.example.medicinalLeafScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CYWc0blcc8TliRxoByehgZjcs-V8Kxg',
    appId: '1:427061760676:web:d57b9eef1fb43f20540c31',
    messagingSenderId: '427061760676',
    projectId: 'medicinal-leaf-scan',
    authDomain: 'medicinal-leaf-scan.firebaseapp.com',
    storageBucket: 'medicinal-leaf-scan.firebasestorage.app',
    measurementId: 'G-9NSKTZJHH0',
  );
}
